//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap armour_image {
            get {
                object obj = ResourceManager.GetObject("armour_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap attack_image {
            get {
                object obj = ResourceManager.GetObject("attack_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap auto_image {
            get {
                object obj = ResourceManager.GetObject("auto_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buy_image {
            get {
                object obj = ResourceManager.GetObject("buy_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fight_image {
            get {
                object obj = ResourceManager.GetObject("fight_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap info_image {
            get {
                object obj = ResourceManager.GetObject("info_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap item_image {
            get {
                object obj = ResourceManager.GetObject("item_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;items&gt;
        ///  &lt;id0 name=&quot;None&quot; weight=&quot;0&quot; value=&quot;0&quot; type=&quot;none&quot;/&gt;
        ///  &lt;id1 name=&quot;Dagger&quot; weight=&quot;1&quot; value=&quot;1&quot; type=&quot;weapon&quot; damage=&quot;1&quot;/&gt;
        ///  &lt;id2 name=&quot;Shortsword&quot; weight=&quot;3&quot; value=&quot;4&quot; type=&quot;weapon&quot; damage=&quot;2&quot;/&gt;
        ///  &lt;id3 name=&quot;Longsword&quot; weight=&quot;5&quot; value=&quot;10&quot; type=&quot;weapon&quot; damage=&quot;3&quot;/&gt;
        ///  &lt;id4 name=&quot;Leather&quot; weight=&quot;10&quot; value=&quot;2&quot; type=&quot;armour&quot; protection=&quot;1&quot;/&gt;
        ///  &lt;id5 name=&quot;Chainmail&quot; weight=&quot;25&quot; value=&quot;6&quot; type=&quot;armour&quot; protection=&quot;2&quot;/&gt;
        ///  &lt;id6 name=&quot;Platemail&quot; weight=&quot;50&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap leave_image {
            get {
                object obj = ResourceManager.GetObject("leave_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap load_image {
            get {
                object obj = ResourceManager.GetObject("load_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;monsters&gt;
        ///  &lt;id0 name=&quot;fluffy bunny&quot; hp=&quot;3&quot; xp=&quot;5&quot; gold=&quot;0&quot; accuracy=&quot;60&quot; damage=&quot;1&quot; speed=&quot;5&quot; image=&quot;rabbit_image&quot;/&gt;
        ///  &lt;id1 name=&quot;landwhale&quot; hp=&quot;20&quot; xp=&quot;10&quot; gold=&quot;20&quot; damage=&quot;4&quot; accuracy=&quot;40&quot; speed=&quot;3&quot; image=&quot;landwhale_image&quot;/&gt;
        ///  &lt;id2 name=&quot;archaeopteryx&quot; hp=&quot;5&quot; xp=&quot;10&quot; gold=&quot;10&quot; damage=&quot;3&quot; accuracy=&quot;70&quot; speed=&quot;9&quot; image=&quot;archaeopteryx_image&quot;/&gt;
        ///  &lt;id3 name=&quot;burning bush&quot; hp=&quot;10&quot; xp=&quot;10&quot; gold=&quot;15&quot; damage=&quot;6&quot; accuracy=&quot;20&quot; speed=&quot;1&quot; image=&quot;bush_image&quot;/&gt;
        ///&lt;/monster [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monsters {
            get {
                return ResourceManager.GetString("monsters", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap mystery_monster_image {
            get {
                object obj = ResourceManager.GetObject("mystery_monster_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap new_image {
            get {
                object obj = ResourceManager.GetObject("new_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap player_image {
            get {
                object obj = ResourceManager.GetObject("player_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap potion_image {
            get {
                object obj = ResourceManager.GetObject("potion_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap quit_image {
            get {
                object obj = ResourceManager.GetObject("quit_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rabbit_image {
            get {
                object obj = ResourceManager.GetObject("rabbit_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap run_image {
            get {
                object obj = ResourceManager.GetObject("run_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save_image {
            get {
                object obj = ResourceManager.GetObject("save_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sell_image {
            get {
                object obj = ResourceManager.GetObject("sell_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shop_image {
            get {
                object obj = ResourceManager.GetObject("shop_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stop_image {
            get {
                object obj = ResourceManager.GetObject("stop_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap weapon_image {
            get {
                object obj = ResourceManager.GetObject("weapon_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
